import streamlit as st
import pandas as pd
import joblib

@st.cache_resource
def load_model():
    model = joblib.load("heart_svm_model.pkl")
    return model

model = load_model()
feature_names = model.feature_names_in_

st.set_page_config(page_title="Heart Disease Risk Demo", page_icon="❤️", layout="centered")

st.title("Heart Disease Risk Predictor (Demo)")
st.write("""
This app uses an **SVM model** trained on the Kaggle heart disease dataset  
to estimate the **probability of heart disease** from the inputs you provide.

⚠ **This is a demonstration for coursework/research only and must NOT be used for real medical diagnosis or treatment.**
""")

st.sidebar.header("Input your information")

age = st.sidebar.number_input("Age (years)", min_value=18, max_value=100, value=50, step=1)
sex = st.sidebar.selectbox("Sex (0 = female, 1 = male)", options=[0, 1], index=1)
cp = st.sidebar.selectbox("Chest pain type (cp)", options=[0, 1, 2, 3], index=0)
trestbps = st.sidebar.number_input("Resting blood pressure (trestbps)", min_value=70.0, max_value=250.0, value=130.0, step=1.0)
chol = st.sidebar.number_input("Serum cholestoral in mg/dl (chol)", min_value=100.0, max_value=600.0, value=240.0, step=1.0)
fbs = st.sidebar.selectbox("Fasting blood sugar > 120 mg/dl? (fbs)", options=[0, 1], index=0)
restecg = st.sidebar.selectbox("Resting electrocardiographic results (restecg)", options=[0, 1, 2], index=0)
thalachh = st.sidebar.number_input("Maximum heart rate achieved (thalachh)", min_value=60.0, max_value=250.0, value=150.0, step=1.0)
exang = st.sidebar.selectbox("Exercise induced angina? (exang)", options=[0, 1], index=0)
oldpeak = st.sidebar.number_input("ST depression induced by exercise (oldpeak)", min_value=0.0, max_value=10.0, value=1.0, step=0.1)
slope = st.sidebar.selectbox("Slope of the peak exercise ST segment (slope)", options=[0, 1, 2], index=1)
ca = st.sidebar.selectbox("Number of major vessels (ca)", options=[0, 1, 2, 3, 4], index=0)
thal = st.sidebar.selectbox("Thal (thal)", options=[0, 1, 2, 3], index=2)

input_dict = {
    "age": age,
    "sex": sex,
    "cp": cp,
    "trestbps": trestbps,
    "chol": chol,
    "fbs": fbs,
    "restecg": restecg,
    "thalachh": thalachh,
    "exang": exang,
    "oldpeak": oldpeak,
    "slope": slope,
    "ca": ca,
    "thal": thal,
}

data_row = {name: input_dict[name] for name in feature_names}
X_input = pd.DataFrame([data_row])

st.subheader("Input to the model")
st.write(X_input)

if st.button("Predict risk"):
    proba = model.predict_proba(X_input)[0][1]
    proba_percent = proba * 100

    if proba < 0.5:
        risk_level = "Low"
        color = "🟢"
    elif proba < 0.8:
        risk_level = "Medium"
        color = "🟡"
    else:
        risk_level = "High"
        color = "🔴"

    st.subheader("Prediction result")
    st.markdown(f"**Estimated probability of heart disease: `{proba_percent:.1f}%`**")
    st.markdown(f"**Risk level: {color} {risk_level}**")

    st.caption("""
    This result is generated by a machine-learning model trained on the Kaggle Heart Disease dataset.
It must NOT be used as a substitute for professional medical advice, diagnosis, or treatment.
    """)
else:
    st.info("Please enter your information on the left and click **Predict risk**")
